"""Generate Sterling MRO's portal-generated PDF PO — Phase 3.2 quirky variant.

Sterling MRO routes all POs through their procurement portal ("SPP v4.2"),
which emits a machine-generated PDF from a no-reply mailbox. The file reads
differently from Patterson's hand-cut ERP PDF: enterprise portal aesthetic,
terminology drift (`Buyer Contact` instead of `Buyer`, `Supplier` instead of
`Vendor`, `Delivery By` instead of `Required By`), column ordering inherited
from the portal's internal data dictionary (UOM ahead of Qty), and a
third-party AP-processor billing instruction in the footer.

Realism anchors:

1.  **UOM column BEFORE Qty** in the line table. Enterprise portal templates
    sometimes follow their data-dictionary field order rather than human
    reading order. An extractor that assumes `Qty then UOM` column adjacency
    mis-reads every row.
2.  **Label quirks.** `PO No`, `Buyer Contact`, `Supplier`, `Delivery By`,
    `Unit`, `Ln` — every label is slightly off from Patterson's canonical
    vocabulary. Forces semantic (not positional) label matching.
3.  **Third-party remit-to footer.** Sterling pays through Axia Financial
    Services, a common mid-market AP outsourcer. Agent must not confuse the
    remit-to block with the bill-to address — they're different legal entities.
4.  **Portal boilerplate.** "Generated by SPP v4.2 — Do not reply to sender"
    is the automated-origin tell.
5.  **Canonical SKUs.** Sterling has no `sku_aliases`; they reference
    Grafton-Reese part numbers directly.
6.  **Nine lines** per SESSION_HANDOFF §6 row 3.2.
7.  **No contract pricing** — Grafton-Reese list to the cent.

Run with: ``uv run python -m scripts.generators.pdf_sterling_portal``
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


@dataclass(frozen=True)
class Line:
    sku: str
    description: str
    uom: str     # note: UOM precedes qty in Sterling's column order
    qty: int
    unit_cost: float


LINES: tuple[Line, ...] = (
    Line("FST-HCS-050-13-200-G5Z",  "Hex Cap Screw 1/2-13 x 2\" Gr5 Zinc",     "EA",  400,  0.34),
    Line("FST-HXN-050-13-G5Z",      "Hex Nut 1/2-13 Gr5 Zinc",                 "EA",  800,  0.11),
    Line("FST-FWS-050-SAE-S18",     "Flat Washer 1/2\" SAE 18-8 SS",           "EA",  600,  0.09),
    Line("FST-SHC-025-20-125-AB",   "SHCS 1/4-20 x 1-1/4\" Alloy Black Oxide", "EA",  500,  0.19),
    Line("FST-SMS-010-16-100-ZT3",  "Self-Drill Tek #10-16 x 1\" HWH Zn T3",   "EA", 1000,  0.08),
    Line("PNM-PCS-025-025N-BR",     "Push-Connect Str 1/4 Tube x 1/4 NPT Br",  "EA",   30,  4.12),
    Line("PNM-QCI-025N-STL",        "QC Coupler Ind 1/4 NPT F Steel",          "EA",   20,  7.20),
    Line("PNM-TBE-PU-025-100FT-BL", "PU Tubing 1/4\" OD 100 ft roll Blue",     "RL",    3, 32.40),
    Line("PNM-MUF-025N-BRZ",        "Muffler 1/4 NPT M Sintered Bronze",       "EA",   50,  3.25),
)

PO_NBR = "SMS-114832"
PO_DATE = "04/15/2026"
DELIV_BY = "05/06/2026"
SHIP_TO_CODE = "STER-BHM"
SHIP_TO_ADDR = "4729 1st Avenue North, Dock A, Birmingham AL 35222"
BUYER_NAME = "Priya Rajan"
BUYER_TITLE = "Buyer"
BUYER_EMAIL = "prajan@sterlingmro.com"
BUYER_PHONE = "(205) 326-7410"
TERMS = "Net 30"
REMIT_LINES = (
    "Sterling MRO Solutions  c/o Axia Financial Services",
    "P.O. Box 840261",
    "Dallas, TX  75284-0261",
    "ACH: Routing 111000614, Acct on file with Supplier AR",
)


def _money(x: float) -> str:
    return f"${x:,.2f}"


def build_story() -> list:
    styles = getSampleStyleSheet()
    body = ParagraphStyle("body", parent=styles["Normal"], fontName="Helvetica", fontSize=9, leading=11)
    small = ParagraphStyle("small", parent=body, fontSize=8, leading=10, textColor=colors.HexColor("#555555"))
    portal_head = ParagraphStyle("ph", parent=body, fontName="Helvetica-Bold", fontSize=15,
                                 textColor=colors.HexColor("#1C4E1F"))
    portal_sub = ParagraphStyle("ps", parent=body, fontName="Helvetica", fontSize=8,
                                textColor=colors.HexColor("#666666"))
    banner = ParagraphStyle("banner", parent=body, fontName="Helvetica-Bold", fontSize=13, alignment=0)
    label = ParagraphStyle("label", parent=body, fontName="Helvetica-Bold", fontSize=9)
    sig = ParagraphStyle("sig", parent=body, fontName="Helvetica-Oblique", fontSize=8.5)
    item_style = ParagraphStyle("item", parent=body, fontName="Courier", fontSize=8, leading=10)
    footer_body = ParagraphStyle("fb", parent=body, fontSize=8, leading=10)

    story: list = []

    # Portal letterhead — different visual identity than Patterson's
    story.append(Paragraph("STERLING MRO SOLUTIONS", portal_head))
    story.append(Paragraph(
        "4729 1st Avenue North, Suite 200  •  Birmingham, AL 35222  •  sterlingmro.com",
        portal_sub,
    ))
    story.append(Paragraph(
        "This document was generated by Sterling Procurement Portal (SPP v4.2). "
        "Do not reply to the sending address.",
        portal_sub,
    ))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Purchase Order", banner))
    story.append(Spacer(1, 6))

    # Metadata — label quirks: "PO No", "Buyer Contact", "Supplier", "Delivery By"
    meta_data = [
        [Paragraph("PO No:", label),          Paragraph(PO_NBR, body),
         Paragraph("Buyer Contact:", label),  Paragraph(BUYER_NAME, body)],
        [Paragraph("PO Date:", label),        Paragraph(PO_DATE, body),
         Paragraph("Email:", label),          Paragraph(BUYER_EMAIL, body)],
        [Paragraph("Delivery By:", label),    Paragraph(DELIV_BY, body),
         Paragraph("Phone:", label),          Paragraph(BUYER_PHONE, body)],
        [Paragraph("Payment Terms:", label),  Paragraph(TERMS, body),
         Paragraph("Supplier:", label),       Paragraph("Grafton-Reese MRO", body)],
        [Paragraph("Ship To:", label),        Paragraph(f"{SHIP_TO_CODE}  —  {SHIP_TO_ADDR}", body),
         Paragraph("", label),                Paragraph("", body)],
    ]
    meta_tbl = Table(meta_data, colWidths=[1.1 * inch, 3.0 * inch, 1.1 * inch, 1.8 * inch])
    meta_tbl.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("SPAN", (1, 4), (3, 4)),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(meta_tbl)
    story.append(Spacer(1, 12))

    # Line table — Ln | Item Code | Description | Unit | Qty | Unit Cost | Total
    header = ["Ln", "Item Code", "Description", "Unit", "Qty", "Unit Cost", "Total"]
    table_data: list[list] = [header]
    subtotal = 0.0
    for i, ln in enumerate(LINES, start=1):
        ext = round(ln.qty * ln.unit_cost, 2)
        subtotal = round(subtotal + ext, 2)
        table_data.append([
            str(i),
            Paragraph(ln.sku, item_style),
            Paragraph(ln.description, body),
            ln.uom,
            f"{ln.qty:,}",
            _money(ln.unit_cost),
            _money(ext),
        ])

    line_tbl = Table(
        table_data,
        colWidths=[0.35 * inch, 1.75 * inch, 2.35 * inch, 0.5 * inch, 0.55 * inch, 0.75 * inch, 0.8 * inch],
        repeatRows=1,
    )
    line_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1C4E1F")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("ALIGN", (3, 1), (3, -1), "CENTER"),          # unit
        ("ALIGN", (4, 1), (4, -1), "RIGHT"),           # qty
        ("ALIGN", (5, 1), (6, -1), "RIGHT"),           # prices
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#999999")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F2F7F3")]),
    ]))
    story.append(line_tbl)
    story.append(Spacer(1, 8))

    # Totals
    totals_data = [
        ["", "", "Subtotal", _money(subtotal)],
        ["", "", "Sales Tax (exempt)", _money(0.00)],
        ["", "", "TOTAL", _money(subtotal)],
    ]
    totals_tbl = Table(totals_data, colWidths=[3.4 * inch, 1.5 * inch, 1.4 * inch, 0.75 * inch])
    totals_tbl.setStyle(TableStyle([
        ("ALIGN", (2, 0), (-1, -1), "RIGHT"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (2, 2), (-1, 2), "Helvetica-Bold"),
        ("LINEABOVE", (2, 2), (-1, 2), 0.5, colors.black),
        ("LINEBELOW", (2, 2), (-1, 2), 1.2, colors.black),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(totals_tbl)
    story.append(Spacer(1, 20))

    # Heavy footer with 3rd-party AP routing — a real Sterling-portal tell
    story.append(Paragraph("<b>REMIT PAYMENT TO</b>", footer_body))
    for rl in REMIT_LINES:
        story.append(Paragraph(rl, footer_body))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "<b>Do NOT remit payment to the Birmingham address.</b> All invoices must be "
        "routed through Axia Financial Services for accounts-payable processing. "
        "Questions regarding remittance: ap-support@axiafinancial.com.",
        footer_body,
    ))
    story.append(Spacer(1, 10))
    story.append(Paragraph(
        f"Acknowledge this PO within 24 hours to {BUYER_EMAIL}. Include PO No {PO_NBR} "
        "and expected ship date. Portal ID: SPP-PO-{PO_NBR}-2026Q2.",
        small,
    ))
    story.append(Spacer(1, 12))
    story.append(Paragraph(
        "Authorized by Sterling Procurement Portal (auto-generated) on behalf of "
        f"{BUYER_NAME}, {BUYER_TITLE}",
        sig,
    ))

    return story


def _on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(colors.HexColor("#777777"))
    canvas.drawString(0.75 * inch, 0.5 * inch, f"Sterling MRO Solutions  •  PO {PO_NBR}  •  SPP v4.2")
    canvas.drawRightString(LETTER[0] - 0.75 * inch, 0.5 * inch, f"Page {doc.page}")
    canvas.restoreState()


def main() -> Path:
    out = Path(__file__).resolve().parents[2] / "data" / "pdf" / "sterling_po-SMS-114832.pdf"
    out.parent.mkdir(parents=True, exist_ok=True)
    doc = BaseDocTemplate(
        str(out),
        pagesize=LETTER,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.6 * inch,
        bottomMargin=0.75 * inch,
        title=f"Sterling {PO_NBR}",
        author="Sterling Procurement Portal",
        subject=f"Purchase Order {PO_NBR}",
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="normal")
    doc.addPageTemplates([PageTemplate(id="main", frames=frame, onPage=_on_page)])
    doc.build(build_story())
    return out


if __name__ == "__main__":
    path = main()
    print(f"wrote: {path}")
